import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdir, mkdtemp } from 'node:fs/promises';
import { resolve } from 'node:path';
import { chromium } from 'playwright';

const output = resolve('cpm/data');
await mkdir(output, { recursive: true });
const testDir = await mkdtemp(resolve(output, 'browser-test-'));
const server = spawn('D:/anaconda/envs/xmer-annotation/python.exe', ['cpm/server.py', '--port', '5183', '--db', resolve(testDir, 'test.sqlite3')], { windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] });
await new Promise((yes, no) => { server.stdout.once('data', yes); server.once('error', no); server.once('exit', code => no(new Error(`Test API exited ${code}`))); });
let browser;
try {
  browser = await chromium.launch({ channel: 'msedge' });
  const page = await browser.newPage({ viewport: { width: 1512, height: 1100 } });
  const errors = [];
  const forbidden = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('request', req => { if (/\/annotation\/|\/api\//.test(req.url())) forbidden.push(req.url()); });
  await page.route('**/cpm-api/**', async route => {
    const url = new URL(route.request().url()); url.port = '5183';
    await route.fulfill({ response: await route.fetch({ url: url.toString() }) });
  });
  await page.goto('http://127.0.0.1:5180/');
  await page.getByRole('heading', { name: '看见事实，核对情境' }).waitFor();
  await page.locator('video').evaluate(v => new Promise(resolve => { if (v.readyState >= 2) resolve(); else v.addEventListener('loadeddata', resolve, { once: true }); }));
  await page.screenshot({ path: 'artifacts/cpm-preview.png', fullPage: true });
  await page.locator('#card-role').fill('修改后的模拟角色');
  await page.reload();
  await page.getByRole('heading', { name: '看见事实，核对情境' }).waitFor();
  assert.equal(await page.locator('#card-role').inputValue(), '修改后的模拟角色');
  await page.getByRole('button', { name: '保存草稿', exact: true }).click();
  await page.getByText('草稿已存入数据库 · 版本 1', { exact: true }).waitFor();
  await page.getByRole('combobox', { name: '切换模拟标注者' }).selectOption('CPM-02');
  await page.getByRole('heading', { name: '看见事实，核对情境' }).waitFor();
  assert.equal(await page.locator('#card-role').inputValue(), '队长，与采访者交谈');
  await page.getByRole('combobox', { name: '切换模拟标注者' }).selectOption('CPM-01');
  await page.getByRole('heading', { name: '看见事实，核对情境' }).waitFor();
  assert.equal(await page.locator('#card-role').inputValue(), '修改后的模拟角色');
  await page.getByRole('button', { name: /动态与提交/ }).click();
  await page.getByRole('button', { name: '提交标注', exact: true }).click();
  await page.getByRole('alert').waitFor();
  assert.match(await page.getByRole('alert').textContent(), /请选择 R/);
  await page.getByRole('button', { name: '关闭错误' }).click();
  await page.getByRole('button', { name: /场景核对/ }).click();
  for (const button of await page.getByRole('button', { name: '确认', exact: true }).all()) await button.click();
  await page.getByRole('button', { name: '片段外被明确提及', exact: true }).click();
  await page.locator('.evidence-card').first().getByRole('checkbox', { name: '已核对' }).check();
  await page.getByRole('button', { name: '下一步', exact: true }).click();
  const ratings = page.locator('.rating-card');
  await ratings.nth(0).getByRole('button', { name: /0.*中等相关/ }).click();
  await ratings.nth(0).getByRole('checkbox', { name: 'E01 · 文本' }).check();
  for (let index = 1; index < 4; index++) await ratings.nth(index).getByRole('button', { name: /信息不足/ }).click();
  await page.screenshot({ path: 'artifacts/cpm-ratings.png', fullPage: true });
  await page.getByRole('button', { name: '下一步', exact: true }).click();
  await page.getByRole('button', { name: '未确认冲突', exact: true }).click();
  await page.getByRole('button', { name: '信息不足', exact: true }).click();
  await page.getByRole('button', { name: '下一步', exact: true }).click();
  await page.getByRole('button', { name: '未见明确变化', exact: true }).click();
  await page.getByRole('button', { name: '提交标注', exact: true }).click();
  await page.getByText('已提交 · 版本 2', { exact: true }).waitFor();
  const exported = await (await fetch('http://127.0.0.1:5183/cpm-api/export')).json();
  assert.equal(exported.records.length, 2);
  assert.equal(exported.assignments.length, 720);
  assert.equal(exported.records[1].payload.ratings.R.value, 0);
  assert.equal(exported.records[1].payload.ratings.I.value, null);
  assert.equal(exported.records[1].payload.ratings.I.state, 'unknown');
  assert.equal(exported.records[1].task_id, 'CPM-01:CPM-S0001');
  await page.getByRole('button', { name: '样本与数据管理', exact: true }).click();
  await page.getByRole('heading', { name: '样本与数据管理', exact: true }).waitFor();
  await page.getByText('版本 2', { exact: true }).waitFor();
  await page.screenshot({ path: 'artifacts/cpm-management.png', fullPage: true });
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: '导出数据', exact: true }).click();
  const download = await downloadPromise;
  assert.match(download.suggestedFilename(), /CPM-demo-export/);
  await page.getByRole('button', { name: '标注工作台', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'artifacts/cpm-mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, 'Mobile must not overflow horizontally');
  assert.deepEqual(errors, []);
  assert.deepEqual(forbidden, []);
  console.log('PASS: page render, local recovery, database draft, annotator isolation, incomplete submission rejected, zero and unknown, full submission, management, export, mobile width, no VA requests, no browser errors.');
  console.log(`Isolated browser test database: ${testDir}`);
} finally {
  await browser?.close();
  server.kill();
}
