"""add task display_id

Revision ID: 22a6741867d8
Revises: a5434311ec63
Create Date: 2026-09-14 11:15:53.126264
"""
from alembic import op
import sqlalchemy as sa


revision = '22a6741867d8'
down_revision = 'a5434311ec63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_id', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_display_id'), ['display_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_display_id'))
        batch_op.drop_column('display_id')

    # ### end Alembic commands ###
