"""baseline: V2 schema

Revision ID: a5434311ec63
Revises: 
Create Date: 2026-09-13 13:07:27.545202
"""
from alembic import op
import sqlalchemy as sa
from app.models import JsonCol

revision = 'a5434311ec63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotators',
    sa.Column('annotator_id', sa.Text(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('phase', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("phase IN ('pilot', 'training', 'main')", name='ck_annotators_phase'),
    sa.PrimaryKeyConstraint('annotator_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('media_id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('modality', sa.Text(), nullable=False),
    sa.Column('src', sa.Text(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('timeline_origin', sa.Float(), nullable=False),
    sa.Column('speaker_ref_src', sa.Text(), nullable=True),
    sa.Column('speaker_name', sa.Text(), nullable=True),
    sa.CheckConstraint("modality IN ('visual', 'audio', 'text', 'audiovisual')", name='ck_tasks_modality'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('assignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('annotator_id', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('phase', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_anchor', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("phase IN ('pilot', 'training', 'main')", name='ck_assignments_phase'),
    sa.ForeignKeyConstraint(['annotator_id'], ['annotators.annotator_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('assignment_id'),
    sa.UniqueConstraint('annotator_id', 'task_id', 'phase', name='uq_assignments_annotator_task')
    )
    op.create_table('attempts',
    sa.Column('attempt_id', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('annotator_id', sa.Text(), nullable=False),
    sa.Column('media_id', sa.Text(), nullable=False),
    sa.Column('modality', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('task_snapshot', JsonCol, nullable=False),
    sa.Column('events', JsonCol, nullable=False),
    sa.Column('sample_rate_hz', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('last_media_time', sa.Float(), nullable=False),
    sa.Column('server_received_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("modality IN ('visual', 'audio', 'text', 'audiovisual')", name='ck_attempts_modality'),
    sa.CheckConstraint("mode IN ('preview', 'annotation')", name='ck_attempts_mode'),
    sa.CheckConstraint("status IN ('recording', 'paused', 'completed', 'interrupted')", name='ck_attempts_status'),
    sa.ForeignKeyConstraint(['annotator_id'], ['annotators.annotator_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_table('attempt_flags',
    sa.Column('flag_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Text(), nullable=False),
    sa.Column('flag', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('flagged_by', sa.Text(), nullable=True),
    sa.Column('flagged_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("flag IN ('ok', 'low_quality', 'void')", name='ck_attempt_flags_flag'),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.attempt_id'], ),
    sa.PrimaryKeyConstraint('flag_id')
    )
    op.create_table('sample_chunks',
    sa.Column('attempt_id', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('samples', JsonCol, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.attempt_id'], ),
    sa.PrimaryKeyConstraint('attempt_id', 'chunk_index')
    )
    op.create_table('submissions',
    sa.Column('submission_id', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('annotator_id', sa.Text(), nullable=False),
    sa.Column('attempt_id', sa.Text(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('previous_submission_id', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['annotator_id'], ['annotators.annotator_id'], ),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.attempt_id'], ),
    sa.ForeignKeyConstraint(['previous_submission_id'], ['submissions.submission_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('submission_id'),
    sa.UniqueConstraint('annotator_id', 'task_id', 'revision', name='uq_submissions_revision'),
    sa.UniqueConstraint('attempt_id', name='uq_submissions_attempt')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissions')
    op.drop_table('sample_chunks')
    op.drop_table('attempt_flags')
    op.drop_table('attempts')
    op.drop_table('assignments')
    op.drop_table('tasks')
    op.drop_table('annotators')
    # ### end Alembic commands ###
